### ISSUE TITLE
Docs: [안성희] Local Stack 실행과정

### ISSUE THREAD

**Issue by AnnSungHee** [Personal-Work-Store/Youth-Future-Plus-Coupon-Admin#27]
# LocalStack이란?
LocalStack은 AWS의 다양한 클라우드 서비스를 로컬 개발 환경에서 에뮬레이션할 수 있도록 해주는 오픈소스 소프트웨어
AWS에 접속하지 않고도 S3, DynamoDB, SQS 등 주요 서비스를 내 컴퓨터나 CI 환경에서 모방해 개발, 테스트, 통합 작업을 가능하게 함

# LocalStack 실행과정
LocalStack은 실행 방법을 여러가지 형태로 제공함
- LocalStack CLI
- Docker
- Docker Compose
- LocalStack Desktop
  - 회원가입을 하게 되면 무조건 유료 구독제 14일 무료체험을 해야하는데 그러고 싶지 않았음
- pip
  - Window Long Path 오류로 인해 안 함

# Docker Compose로 LocalStack 사용하기
```yaml
services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```
관리를 편하게 하기 위해 프로젝트 루트 경로에 docker-compose.yml 생성
```
docker compose up
```
docker compose 파일을 기준으로 컨테이너 생성
```
pip install awscli
pip install awscli-local
```
aws 명령어를 사용하기 위한 의존성 설치
```
aws configure
AWS Access Key ID [None]: test
AWS Secret Access Key [None]: test
Default region name [None]: us-east-1
Default output format [None]: json
```
aws 기본 설정 수행
